version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports: ["9200:9200"]

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports: ["5044:5044"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    ports: ["5601:5601"]

  prometheus:
    image: prom/prometheus:2.35.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:9.2.0
    ports: ["3000:3000"]
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  es_data:
  grafana_data:
